module version
	implicit none
	
	!!! DO NOT EDIT THIS FILE !!! 
	!This file is generated automatically by running version_header
	
	! Local code information:
	character(80) :: local_name = '@@     MUT_batch: Batch processor for MUT, USGS_1 and Tecplot           @@'
	character(80) :: local_version = '1385'
	character(80) :: build_date	   = '2025'
	character(80) :: build_specific_info   = '64bit'
	character(80) :: MUTDir	   = 'C:\MUT\MUT_Examples-main\_MUT_USERBIN'
	
	! Repository information:
	character(80) :: repo_1= 'Path: .'
	character(80) :: repo_2= 'Working Copy Root Path: D:\hgs\trunk'
	character(80) :: repo_3= 'URL: svn+ssh://meinzer/hgs/trunk'
	character(80) :: repo_4= 'Repository Root: svn+ssh://meinzer/hgs'
	character(80) :: repo_5= 'Repository UUID: cbdd0707-f681-3e47-8d16-8894fab75c47'
	character(80) :: repo_6= 'Revision: 1385'
	character(80) :: repo_7= 'Node Kind: directory'
	character(80) :: repo_8= 'Schedule: normal'
	character(80) :: repo_9= 'Last Changed Author: mclaren'
end module version
